from Automata import Automata
from automato.states import qo, qnumber, qlparen, qlessequal, qgreaterequal, qlbraces, qrparen, qequal, qdifferent, q0, q1, q2, q3, q4, q5, q6, q7, q8, q9, q10, q11, \
    q12, q13, q14, q15, q16, q17, q18, q19, q20, q21, q22, q23, q24, q25, q26, q27, q28, q29, q30
from constants import ALFABETO_ENTRADA

automato = Automata(ALFABETO_ENTRADA, q0, qo)

automato.addState(qlparen)
automato.addState(qlbraces)
automato.addState(qrparen)
automato.addState(qnumber)
automato.addState(qlessequal)
automato.addState(qgreaterequal)
automato.addState(qequal)
automato.addState(qdifferent)

automato.addState(q0)
automato.addState(q1)
automato.addState(q2)
automato.addState(q3)
automato.addState(q4)
automato.addState(q5)
automato.addState(q6)
automato.addState(q7)
automato.addState(q8)
automato.addState(q9)
automato.addState(q10)
automato.addState(q11)
automato.addState(q12)
automato.addState(q13)
automato.addState(q14)
automato.addState(q15)
automato.addState(q16)
automato.addState(q17)
automato.addState(q18)
automato.addState(q19)
automato.addState(q20)
automato.addState(q21)
automato.addState(q22)
automato.addState(q23)
automato.addState(q24)
automato.addState(q25)
automato.addState(q26)
automato.addState(q27)
automato.addState(q28)
automato.addState(q29)
automato.addState(q30)

mealyAutomato = automato.getMealyAutomata()
